name: AxPlayerWarps
version: '${project.version}'
main: com.artillexstudios.axplayerwarps.AxPlayerWarps
api-version: '1.18'
folia-supported: true

permissions:
  axplayerwarps.open:
    default: true
  axplayerwarps.use:
    default: true
  axplayerwarps.delete:
    default: true
  axplayerwarps.edit:
    default: true
  axplayerwarps.info:
    default: true
  axplayerwarps.open.other:
    default: op
  axplayerwarps.create:
    default: true
  axplayerwarps.create.other:
    default: op
  axplayerwarps.reload:
    default: op
  axplayerwarps.warps.1:
    default: true
  axplayerwarps.delay-bypass:
    default: op

softdepend:
  - PlaceholderAPI